# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmhi < Formula
  desc "A CLI for managing a T-Mobile Home Internet gateway."
  homepage "https://github.com/cloud-unpacked/tmhi"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/cloud-unpacked/tmhi/releases/download/v0.1.2/tmhi-v0.1.2-macos-arm64.tar.gz"
      sha256 "4ae4cc763093c7f84fb97e03f852db7a9e5ac82a131f3699cf6e81ac32009b80"

      def install
        bin.install "tmhi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloud-unpacked/tmhi/releases/download/v0.1.2/tmhi-v0.1.2-macos-amd64.tar.gz"
      sha256 "fad87866a628f539f969e37dcc7f25f5fa134b6b66991135257a953d0ee791b3"

      def install
        bin.install "tmhi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cloud-unpacked/tmhi/releases/download/v0.1.2/tmhi-v0.1.2-linux-arm64.tar.gz"
      sha256 "dfbf8e782e4ed72629bb65f083c181070a39ae75f3d82f77852d2478e2acfb55"

      def install
        bin.install "tmhi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/cloud-unpacked/tmhi/releases/download/v0.1.2/tmhi-v0.1.2-linux-amd64.tar.gz"
      sha256 "0678b0fbec8e229cbb6482dc533fa22f17b58efc26c6f3ad28101159b789ab30"

      def install
        bin.install "tmhi"
      end
    end
  end

  test do
    system "#{bin}/tmhi", "help"
  end
end
